declare const REACT_APP_ENV: 'test' | 'dev' | 'pre' | 'pro' | 'beta' | false;
declare const API_URL: string;
declare const MICROBOOK_URL: string;
declare const DATA_DOWNLOAD_URL: string;
declare const RSA_PUBLIC_KEY: string;
declare const PRIMARYCOLOR: string;
declare const MAINCOLOR2: string;
declare const ACTIVITY_CENTER: string;
declare const AI_URL: string;
declare const AI_API: string;
declare const aliyun: any;
declare const TMap: any;
